language: node_js

node_js:
  - "0.10.33"

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -q
- sudo apt-get install -y libstdc++6

install:
- npm install --loglevel=http --fallback-to-build=false --no-rollback
- for i in $(ls node_modules/); do (if [[ $i != "mapnik-omnivore" ]]; then cd node_modules/$i && npm install --no-rollback $(node -e "console.log(Object.keys(require('./package.json').devDependencies).join(' '))"); fi); done || true
- (cd node_modules/mapnik-omnivore && npm install tape coveralls istanbul http://mapbox-npm.s3.amazonaws.com/package/mapnik-test-data-2.0.3-fece0a9c546074a1479e9eae2333184029bb2279.tgz)

before_script:
- npm ls mapnik

script:
- npm test

