language: generic

matrix:
  include:
    - os: osx
      env: NODE_NVM_VERSION="4"
    - os: linux
      sudo: false
      env: NODE_NVM_VERSION="4"
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++6

env:
  global:
   # MapboxAccessToken for tilelive-vector
   - secure: "J6bryOYSIYMroBZdSdlg+zRRhHizJVoXsxhgA8qQrG0VSExga2AEOebarV0JbXNwHRP/fkZeFNAiag9ElAaj4GOMRoyuU3z4CNTqUPuVaghsYetn42NrzNnTIFRUlwOgHyTJACZPIwBWPLjPhRazBlJaF6EjOJbYhwSM7hdsHKo="

before_install:
 - git clone https://github.com/creationix/nvm.git ../.nvm
 - source ../.nvm/nvm.sh
 - nvm install $NODE_NVM_VERSION
 - nvm use $NODE_NVM_VERSION
 - node --version
 - npm --version

install:
 - npm install --fallback-to-build=false

script:
 - npm test

notifications:
  slack:
    secure: LIF6zeIxEJtZKPIAconswMC3D0nrCiH/5kIUVZWJxW1o32YrnMUNXEFhOf740sKQtcU8uDXurss6yKKU/24D1pXPpXt/+QG1WT5+vq3AejcE46FXdbOhcjAukuBxCohiOuwiyJmmGaFDsH4NQ9nA0ROWRjF3wSi/fclik6zFpLQ=

