language: cpp

sudo: false

matrix:
  include:
    - os: osx
      env: NODE_NVM_VERSION="0.10.38"
    - os: linux
      env: NODE_NVM_VERSION="0.10.38"
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++6

env:
  global:
   # https://github.com/mapbox/tilelive-vector/pull/116
   - TILELIVE_VECTOR_NO_AUTH: "true"

before_install:
 - git clone https://github.com/creationix/nvm.git ../.nvm
 - source ../.nvm/nvm.sh
 - nvm install $NODE_NVM_VERSION
 - nvm use $NODE_NVM_VERSION
 - node --version
 - npm --version

install:
 - npm install --loglevel=http --fallback-to-build=false

before_script:
 - npm ls

script:
 - npm test
 - npm dedupe
 - npm test

