language: node_js

node_js:
  - "0.10"
  #- "0.11"

env:
  global:
  - secure: "J6bryOYSIYMroBZdSdlg+zRRhHizJVoXsxhgA8qQrG0VSExga2AEOebarV0JbXNwHRP/fkZeFNAiag9ElAaj4GOMRoyuU3z4CNTqUPuVaghsYetn42NrzNnTIFRUlwOgHyTJACZPIwBWPLjPhRazBlJaF6EjOJbYhwSM7hdsHKo="

sudo: false

before_install:
# install c++11 capable libstdc++ without sudo
- if [[ $(uname -s) == 'Linux' ]]; then wget https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+files/libstdc%2B%2B6_4.8.1-2ubuntu1~12.04_amd64.deb && dpkg -x libstdc++6_4.8.1-2ubuntu1~12.04_amd64.deb ./ && export LD_PRELOAD=$(pwd)/usr/lib/x86_64-linux-gnu/libstdc++.so.6; fi

install:
- npm install --loglevel=http --fallback-to-build=false --no-rollback
- for i in $(ls node_modules/); do (cd node_modules/$i && npm install --no-rollback $(node ../../get-dev-deps.js)); done;
- (cd node_modules/mapnik-omnivore && npm install http://mapbox-npm.s3.amazonaws.com/package/mapnik-test-data-2.0.3-fece0a9c546074a1479e9eae2333184029bb2279.tgz)

before_script:
- npm ls mapnik
- npm dedupe
- npm ls mapnik

script:
- npm test

