language: generic



env:
  global:
   # MapboxAccessToken for tilelive-vector
   - secure: "J6bryOYSIYMroBZdSdlg+zRRhHizJVoXsxhgA8qQrG0VSExga2AEOebarV0JbXNwHRP/fkZeFNAiag9ElAaj4GOMRoyuU3z4CNTqUPuVaghsYetn42NrzNnTIFRUlwOgHyTJACZPIwBWPLjPhRazBlJaF6EjOJbYhwSM7hdsHKo="

before_install:
 - echo $MapboxAccessToken | cut -f 2 -d . | base64 --decode

install:
 - npm install --fallback-to-build=false ${NPM_FLAGS}

script:
 - npm test

notifications:
  slack:
    secure: LIF6zeIxEJtZKPIAconswMC3D0nrCiH/5kIUVZWJxW1o32YrnMUNXEFhOf740sKQtcU8uDXurss6yKKU/24D1pXPpXt/+QG1WT5+vq3AejcE46FXdbOhcjAukuBxCohiOuwiyJmmGaFDsH4NQ9nA0ROWRjF3wSi/fclik6zFpLQ=
